package com.dao;

import com.bean.Privilege;
import com.bean.PrivilegeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    long countByExample(PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    int deleteByExample(PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    int insert(Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    int insertSelective(Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    List<Privilege> selectByExample(PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    Privilege selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") Privilege record, @Param("example") PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    int updateByExample(@Param("record") Privilege record, @Param("example") PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    int updateByPrimaryKeySelective(Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    int updateByPrimaryKey(Privilege record);
}