package com.dao;

import com.bean.Relation;
import com.bean.RelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    long countByExample(RelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    int deleteByExample(RelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    int insert(Relation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    int insertSelective(Relation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    List<Relation> selectByExample(RelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    Relation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") Relation record, @Param("example") RelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    int updateByExample(@Param("record") Relation record, @Param("example") RelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    int updateByPrimaryKeySelective(Relation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    int updateByPrimaryKey(Relation record);
}