package com.dao;

import com.bean.RolePrivilege;
import com.bean.RolePrivilegeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolePrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    long countByExample(RolePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    int deleteByExample(RolePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    int insert(RolePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    int insertSelective(RolePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    List<RolePrivilege> selectByExample(RolePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    RolePrivilege selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") RolePrivilege record, @Param("example") RolePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    int updateByExample(@Param("record") RolePrivilege record, @Param("example") RolePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    int updateByPrimaryKeySelective(RolePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    int updateByPrimaryKey(RolePrivilege record);
}