package com.bean;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.math.BigDecimal;
import java.util.Date;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.name
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.author
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.price
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.time
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.intro
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.image
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.inventory
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    private Integer inventory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.sale
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    private Integer sale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.status
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.category_id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.user_id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.id
     *
     * @return the value of book.id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.id
     *
     * @param id the value for book.id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.name
     *
     * @return the value of book.name
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.name
     *
     * @param name the value for book.name
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.author
     *
     * @return the value of book.author
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.author
     *
     * @param author the value for book.author
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.price
     *
     * @return the value of book.price
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.price
     *
     * @param price the value for book.price
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.time
     *
     * @return the value of book.time
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.time
     *
     * @param time the value for book.time
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.intro
     *
     * @return the value of book.intro
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.intro
     *
     * @param intro the value for book.intro
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.image
     *
     * @return the value of book.image
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.image
     *
     * @param image the value for book.image
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.inventory
     *
     * @return the value of book.inventory
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public Integer getInventory() {
        return inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.inventory
     *
     * @param inventory the value for book.inventory
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public void setInventory(Integer inventory) {
        this.inventory = inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.sale
     *
     * @return the value of book.sale
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public Integer getSale() {
        return sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.sale
     *
     * @param sale the value for book.sale
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public void setSale(Integer sale) {
        this.sale = sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.status
     *
     * @return the value of book.status
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.status
     *
     * @param status the value for book.status
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.category_id
     *
     * @return the value of book.category_id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.category_id
     *
     * @param categoryId the value for book.category_id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.user_id
     *
     * @return the value of book.user_id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.user_id
     *
     * @param userId the value for book.user_id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        return "Book{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", author='" + author + '\'' +
                ", price=" + price +
                ", time=" + time +
                ", intro='" + intro + '\'' +
                ", image='" + image + '\'' +
                ", inventory=" + inventory +
                ", sale=" + sale +
                ", status='" + status + '\'' +
                ", categoryId=" + categoryId +
                ", userId=" + userId +
                '}';
    }
}