package com.bean;

public class Express {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.id
     *
     * @mbg.generated Thu Apr 09 10:12:00 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.express_company
     *
     * @mbg.generated Thu Apr 09 10:12:00 CST 2020
     */
    private String expressCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.order_id
     *
     * @mbg.generated Thu Apr 09 10:12:00 CST 2020
     */
    private Integer orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.id
     *
     * @return the value of express.id
     *
     * @mbg.generated Thu Apr 09 10:12:00 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.id
     *
     * @param id the value for express.id
     *
     * @mbg.generated Thu Apr 09 10:12:00 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.express_company
     *
     * @return the value of express.express_company
     *
     * @mbg.generated Thu Apr 09 10:12:00 CST 2020
     */
    public String getExpressCompany() {
        return expressCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.express_company
     *
     * @param expressCompany the value for express.express_company
     *
     * @mbg.generated Thu Apr 09 10:12:00 CST 2020
     */
    public void setExpressCompany(String expressCompany) {
        this.expressCompany = expressCompany == null ? null : expressCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.order_id
     *
     * @return the value of express.order_id
     *
     * @mbg.generated Thu Apr 09 10:12:00 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.order_id
     *
     * @param orderId the value for express.order_id
     *
     * @mbg.generated Thu Apr 09 10:12:00 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
}