package com.bean;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.id
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.book_id
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.number
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.cost
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    private BigDecimal cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.status
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.submit_time
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date submitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.consignee
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    private String consignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.telephone
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.site_id
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    private Integer siteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.user_id
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.merchant
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    private Integer merchant;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.id
     *
     * @return the value of t_order.id
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.id
     *
     * @param id the value for t_order.id
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.book_id
     *
     * @return the value of t_order.book_id
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.book_id
     *
     * @param bookId the value for t_order.book_id
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.number
     *
     * @return the value of t_order.number
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.number
     *
     * @param number the value for t_order.number
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.cost
     *
     * @return the value of t_order.cost
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.cost
     *
     * @param cost the value for t_order.cost
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.status
     *
     * @return the value of t_order.status
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.status
     *
     * @param status the value for t_order.status
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.submit_time
     *
     * @return the value of t_order.submit_time
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    public Date getSubmitTime() {
        return submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.submit_time
     *
     * @param submitTime the value for t_order.submit_time
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    public void setSubmitTime(Date submitTime) {
        this.submitTime = submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.consignee
     *
     * @return the value of t_order.consignee
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.consignee
     *
     * @param consignee the value for t_order.consignee
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.telephone
     *
     * @return the value of t_order.telephone
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.telephone
     *
     * @param telephone the value for t_order.telephone
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.site_id
     *
     * @return the value of t_order.site_id
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.site_id
     *
     * @param siteId the value for t_order.site_id
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.user_id
     *
     * @return the value of t_order.user_id
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.user_id
     *
     * @param userId the value for t_order.user_id
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.merchant
     *
     * @return the value of t_order.merchant
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    public Integer getMerchant() {
        return merchant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.merchant
     *
     * @param merchant the value for t_order.merchant
     *
     * @mbg.generated Fri Apr 03 11:45:28 CST 2020
     */
    public void setMerchant(Integer merchant) {
        this.merchant = merchant;
    }
}