package com.bean;

public class Privilege {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege.id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege.name
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege.path
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege.parent_id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    private Integer parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege.id
     *
     * @return the value of privilege.id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege.id
     *
     * @param id the value for privilege.id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege.name
     *
     * @return the value of privilege.name
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege.name
     *
     * @param name the value for privilege.name
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege.path
     *
     * @return the value of privilege.path
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege.path
     *
     * @param path the value for privilege.path
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege.parent_id
     *
     * @return the value of privilege.parent_id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege.parent_id
     *
     * @param parentId the value for privilege.parent_id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}