package com.bean;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Refund {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.id
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.reason
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.type
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.time
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.consignee
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    private String consignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.site
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    private String site;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.telephone
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.status
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.result
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.order_status
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.order_id
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    private Integer orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.id
     *
     * @return the value of refund.id
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.id
     *
     * @param id the value for refund.id
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.reason
     *
     * @return the value of refund.reason
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.reason
     *
     * @param reason the value for refund.reason
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.type
     *
     * @return the value of refund.type
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.type
     *
     * @param type the value for refund.type
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.time
     *
     * @return the value of refund.time
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.time
     *
     * @param time the value for refund.time
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.consignee
     *
     * @return the value of refund.consignee
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.consignee
     *
     * @param consignee the value for refund.consignee
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.site
     *
     * @return the value of refund.site
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.site
     *
     * @param site the value for refund.site
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.telephone
     *
     * @return the value of refund.telephone
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.telephone
     *
     * @param telephone the value for refund.telephone
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.status
     *
     * @return the value of refund.status
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.status
     *
     * @param status the value for refund.status
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.result
     *
     * @return the value of refund.result
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.result
     *
     * @param result the value for refund.result
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.order_status
     *
     * @return the value of refund.order_status
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.order_status
     *
     * @param orderStatus the value for refund.order_status
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.order_id
     *
     * @return the value of refund.order_id
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.order_id
     *
     * @param orderId the value for refund.order_id
     *
     * @mbg.generated Tue Apr 21 10:49:58 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
}