package com.bean;

public class Relation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation.id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation.book_id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation.relation_id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    private Integer relationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation.id
     *
     * @return the value of relation.id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation.id
     *
     * @param id the value for relation.id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation.book_id
     *
     * @return the value of relation.book_id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation.book_id
     *
     * @param bookId the value for relation.book_id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation.relation_id
     *
     * @return the value of relation.relation_id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public Integer getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation.relation_id
     *
     * @param relationId the value for relation.relation_id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public void setRelationId(Integer relationId) {
        this.relationId = relationId;
    }
}