package com.bean;

public class RolePrivilege {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_privilege.id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_privilege.role_id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_privilege.privilege_id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    private Integer privilegeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_privilege.id
     *
     * @return the value of role_privilege.id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_privilege.id
     *
     * @param id the value for role_privilege.id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_privilege.role_id
     *
     * @return the value of role_privilege.role_id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_privilege.role_id
     *
     * @param roleId the value for role_privilege.role_id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_privilege.privilege_id
     *
     * @return the value of role_privilege.privilege_id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public Integer getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_privilege.privilege_id
     *
     * @param privilegeId the value for role_privilege.privilege_id
     *
     * @mbg.generated Sun Mar 29 10:21:46 CST 2020
     */
    public void setPrivilegeId(Integer privilegeId) {
        this.privilegeId = privilegeId;
    }
}