package com.bean;

public class ShoppingCart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.id
     *
     * @mbg.generated Wed Apr 01 10:33:55 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.book_id
     *
     * @mbg.generated Wed Apr 01 10:33:55 CST 2020
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.number
     *
     * @mbg.generated Wed Apr 01 10:33:55 CST 2020
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.user_id
     *
     * @mbg.generated Wed Apr 01 10:33:55 CST 2020
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.id
     *
     * @return the value of shopping_cart.id
     *
     * @mbg.generated Wed Apr 01 10:33:55 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.id
     *
     * @param id the value for shopping_cart.id
     *
     * @mbg.generated Wed Apr 01 10:33:55 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.book_id
     *
     * @return the value of shopping_cart.book_id
     *
     * @mbg.generated Wed Apr 01 10:33:55 CST 2020
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.book_id
     *
     * @param bookId the value for shopping_cart.book_id
     *
     * @mbg.generated Wed Apr 01 10:33:55 CST 2020
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.number
     *
     * @return the value of shopping_cart.number
     *
     * @mbg.generated Wed Apr 01 10:33:55 CST 2020
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.number
     *
     * @param number the value for shopping_cart.number
     *
     * @mbg.generated Wed Apr 01 10:33:55 CST 2020
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.user_id
     *
     * @return the value of shopping_cart.user_id
     *
     * @mbg.generated Wed Apr 01 10:33:55 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.user_id
     *
     * @param userId the value for shopping_cart.user_id
     *
     * @mbg.generated Wed Apr 01 10:33:55 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}