package com.bean;

public class Site {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.id
     *
     * @mbg.generated Wed Apr 01 10:33:55 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.name
     *
     * @mbg.generated Wed Apr 01 10:33:55 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.id
     *
     * @return the value of site.id
     *
     * @mbg.generated Wed Apr 01 10:33:55 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.id
     *
     * @param id the value for site.id
     *
     * @mbg.generated Wed Apr 01 10:33:55 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.name
     *
     * @return the value of site.name
     *
     * @mbg.generated Wed Apr 01 10:33:55 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.name
     *
     * @param name the value for site.name
     *
     * @mbg.generated Wed Apr 01 10:33:55 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}